# render.yaml - Free tier configuration
services:
  - type: web
    name: teacher-ai-assistant
    runtime: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///./app.db
      - key: CHROMA_DB_DIR
        value: ./chroma_db
